name: CI – Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: investtrack-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: investtrack-frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint (optional)
        run: npm run lint || true

      - name: Run tests (with coverage)
        run: npm run test -- --coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: investtrack-frontend/coverage/
