title: "InvestTrack"
description: "A Learning Tool to Follow Investors and Market Trends"
baseurl: "/HC26-Raihan-Md-Hamim-Senior-Project"
url: "" 

remote_theme: pages-themes/cayman

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

relative_links:
  enabled: true
  collections: true
