title: "InvestTrack"
description: "A Learning Tool to Follow Investors and Market Trends"
baseurl: "/HC26-Raihan-Md-Hamim-Senior-Project"
url: ""

theme: null


plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

relative_links:
  enabled: true
  collections: true

# Navigation links
nav:
  - title: "Home"
    url: /
  - title: "Proposal"
    url: /proposal
  - title: "Annotated Bibliography"
    url: /annotated
